title: Students for a Deliberative Democracy
description: A Strong Democracy is a Deliberative Democracy
logo:   site-logo.png
disqus_shortname:   s4dd
search: true

paginate: 5

# Owner/author information
owner:
  name:           Students for a Deliberative Democracy
  avatar:
  email:    dgfranklin@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: S4DD_Org
  facebook: s4dd.org
  github:
  linkedin:
  instagram:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Archive
    url: /archive/
  - title: Mailing List Signup
    url: /sign-up
  - title: Google
    url: http://google.com
    external: true

markdown: redcarpet
pygments: true
timezone: America/New_YorkA
baseurl: /s4dd-site

permalink:   /:categories/:title/
